 #FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
 FROM microsoft/dotnet:2.2-sdk AS build
 #WORKDIR /src
 WORKDIR /source
 #这里的后面的 . 就是/source 路径
 #或者 COPY *.csproj /source
 COPY *.csproj .
 RUN dotnet restore
 COPY . .
 # 发布到 /source/out 下
 RUN dotnet publish -c Release -o out
 
 #FROM mcr.microsoft.com/dotnet/core/runtime:2.2
 FROM microsoft/dotnet:2.2-aspnetcore-runtime
 WORKDIR /app
 COPY --from=build /source/out .
 EXPOSE 80
 ENTRYPOINT ["dotnet","Order.Api.dll"]